// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    appMetadata,
    settings,
    workout,
    workoutExercise,
    workoutExerciseParentOrder,
    workoutExerciseNormalizedName,
    workoutSet,
    workoutSetParentOrder,
    session,
    scheduleEntry,
    scheduleEntryDateStatus,
    scheduleEntryWorkout,
    sessionWorkout,
    sessionScheduleEntry,
    sessionChronology,
    sessionResumeStatus,
    scheduleEntryCompletedSessionOnInsert,
    scheduleEntryCompletedSessionOnUpdate,
    sessionCompletedScheduleStatusOnUpdate,
    sessionExercise,
    sessionExerciseParentOrder,
    sessionExerciseNormalizedName,
    sessionSet,
    sessionSetParentOrder,
  ];
  late final Shape0 appMetadata = Shape0(
    source: i0.VersionedTable(
      entityName: 'app_metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape0 settings = Shape0(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 workout = Shape1(
    source: i0.VersionedTable(
      entityName: 'workout',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_2, _column_3, _column_4, _column_5, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 workoutExercise = Shape2(
    source: i0.VersionedTable(
      entityName: 'workout_exercise',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CONSTRAINT workout_exercise_order CHECK(order_index >= 0)',
        'CONSTRAINT workout_exercise_planned_sets CHECK(planned_sets >= 1)',
        'CONSTRAINT workout_exercise_rest CHECK(rest_seconds >= 0)',
        'CONSTRAINT workout_exercise_superset CHECK(superset_group IS NULL OR superset_group >= 0)',
        'CONSTRAINT workout_exercise_rep_fields CHECK((rep_type = \'fixed\' AND target_reps IS NOT NULL AND target_reps >= 1 AND min_reps IS NULL AND max_reps IS NULL)OR(rep_type = \'range\' AND target_reps IS NULL AND min_reps IS NOT NULL AND max_reps IS NOT NULL AND min_reps >= 1 AND max_reps >= min_reps)OR(rep_type = \'amrap\' AND target_reps IS NULL AND min_reps IS NULL AND max_reps IS NULL))',
        'CONSTRAINT workout_exercise_load_fields CHECK((load_type = \'none\' AND weight_canonical_mg IS NULL AND percentage IS NULL AND target_rpe IS NULL AND freeform_text IS NULL)OR(load_type = \'bodyweight\' AND weight_canonical_mg IS NULL AND percentage IS NULL AND target_rpe IS NULL AND freeform_text IS NULL)OR(load_type = \'absolute\' AND weight_canonical_mg IS NOT NULL AND weight_canonical_mg >= 0 AND percentage IS NULL AND target_rpe IS NULL AND freeform_text IS NULL)OR(load_type = \'percentage\' AND percentage IS NOT NULL AND percentage >= 0 AND percentage <= 100 AND weight_canonical_mg IS NULL AND target_rpe IS NULL AND freeform_text IS NULL)OR(load_type = \'target_rpe\' AND target_rpe IS NOT NULL AND target_rpe >= 0 AND target_rpe <= 10 AND weight_canonical_mg IS NULL AND percentage IS NULL AND freeform_text IS NULL)OR(load_type = \'text\' AND freeform_text IS NOT NULL AND length(freeform_text) > 0 AND weight_canonical_mg IS NULL AND percentage IS NULL AND target_rpe IS NULL))',
      ],
      columns: [
        _column_2,
        _column_7,
        _column_3,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index workoutExerciseParentOrder = i1.Index(
    'workout_exercise_parent_order',
    'CREATE UNIQUE INDEX workout_exercise_parent_order ON workout_exercise (workout_id, order_index)',
  );
  final i1.Index workoutExerciseNormalizedName = i1.Index(
    'workout_exercise_normalized_name',
    'CREATE INDEX workout_exercise_normalized_name ON workout_exercise (normalized_name)',
  );
  late final Shape3 workoutSet = Shape3(
    source: i0.VersionedTable(
      entityName: 'workout_set',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CONSTRAINT workout_set_index CHECK(set_index >= 0)',
        'CONSTRAINT workout_set_rest CHECK(rest_seconds >= 0)',
        'CONSTRAINT workout_set_rep_fields CHECK((rep_type = \'fixed\' AND target_reps IS NOT NULL AND target_reps >= 1 AND min_reps IS NULL AND max_reps IS NULL)OR(rep_type = \'range\' AND target_reps IS NULL AND min_reps IS NOT NULL AND max_reps IS NOT NULL AND min_reps >= 1 AND max_reps >= min_reps)OR(rep_type = \'amrap\' AND target_reps IS NULL AND min_reps IS NULL AND max_reps IS NULL))',
        'CONSTRAINT workout_set_load_fields CHECK((load_type = \'none\' AND weight_canonical_mg IS NULL AND percentage IS NULL AND target_rpe IS NULL AND freeform_text IS NULL)OR(load_type = \'bodyweight\' AND weight_canonical_mg IS NULL AND percentage IS NULL AND target_rpe IS NULL AND freeform_text IS NULL)OR(load_type = \'absolute\' AND weight_canonical_mg IS NOT NULL AND weight_canonical_mg >= 0 AND percentage IS NULL AND target_rpe IS NULL AND freeform_text IS NULL)OR(load_type = \'percentage\' AND percentage IS NOT NULL AND percentage >= 0 AND percentage <= 100 AND weight_canonical_mg IS NULL AND target_rpe IS NULL AND freeform_text IS NULL)OR(load_type = \'target_rpe\' AND target_rpe IS NOT NULL AND target_rpe >= 0 AND target_rpe <= 10 AND weight_canonical_mg IS NULL AND percentage IS NULL AND freeform_text IS NULL)OR(load_type = \'text\' AND freeform_text IS NOT NULL AND length(freeform_text) > 0 AND weight_canonical_mg IS NULL AND percentage IS NULL AND target_rpe IS NULL))',
      ],
      columns: [
        _column_2,
        _column_22,
        _column_23,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index workoutSetParentOrder = i1.Index(
    'workout_set_parent_order',
    'CREATE UNIQUE INDEX workout_set_parent_order ON workout_set (workout_exercise_id, set_index)',
  );
  late final Shape4 session = Shape4(
    source: i0.VersionedTable(
      entityName: 'session',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'UNIQUE(id, schedule_entry_id)',
        'CONSTRAINT session_timezone CHECK(length(timezone) > 0)',
        'CONSTRAINT session_status CHECK(status IN (\'draft\', \'running\', \'paused\', \'finished\', \'abandoned\'))',
        'CONSTRAINT session_rest_group CHECK((rest_started_at IS NULL AND rest_duration_seconds IS NULL AND rest_target_at IS NULL)OR(rest_started_at IS NOT NULL AND rest_duration_seconds IS NOT NULL AND rest_duration_seconds >= 0 AND rest_target_at IS NOT NULL AND rest_target_at = rest_started_at + rest_duration_seconds))',
      ],
      columns: [
        _column_2,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_4,
        _column_31,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 scheduleEntry = Shape5(
    source: i0.VersionedTable(
      entityName: 'schedule_entry',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'FOREIGN KEY(session_id, id)REFERENCES session(id, schedule_entry_id)ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED',
        'CONSTRAINT schedule_entry_date CHECK(date GLOB \'[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]\' AND date(date) = date)',
        'CONSTRAINT schedule_entry_start_time CHECK(start_time IS NULL OR(start_time >= 0 AND start_time <= 1439))',
        'CONSTRAINT schedule_entry_status_session CHECK((status = \'planned\' AND session_id IS NULL)OR(status = \'skipped\' AND session_id IS NULL)OR(status = \'completed_by_session\' AND session_id IS NOT NULL))',
      ],
      columns: [
        _column_2,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_30,
        _column_38,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index scheduleEntryDateStatus = i1.Index(
    'schedule_entry_date_status',
    'CREATE INDEX schedule_entry_date_status ON schedule_entry (date, status)',
  );
  final i1.Index scheduleEntryWorkout = i1.Index(
    'schedule_entry_workout',
    'CREATE INDEX schedule_entry_workout ON schedule_entry (workout_id)',
  );
  final i1.Index sessionWorkout = i1.Index(
    'session_workout',
    'CREATE INDEX session_workout ON session (workout_id)',
  );
  final i1.Index sessionScheduleEntry = i1.Index(
    'session_schedule_entry',
    'CREATE INDEX session_schedule_entry ON session (schedule_entry_id)',
  );
  final i1.Index sessionChronology = i1.Index(
    'session_chronology',
    'CREATE INDEX session_chronology ON session (started_at)',
  );
  final i1.Index sessionResumeStatus = i1.Index(
    'session_resume_status',
    'CREATE INDEX session_resume_status ON session (status) WHERE status IN (\'running\', \'paused\')',
  );
  final i1.Trigger scheduleEntryCompletedSessionOnInsert = i1.Trigger(
    'CREATE TRIGGER schedule_entry_completed_session_on_insert BEFORE INSERT ON schedule_entry WHEN NEW.status = \'completed_by_session\' AND NOT EXISTS (SELECT 1 FROM session WHERE id = NEW.session_id AND schedule_entry_id = NEW.id AND workout_id = NEW.workout_id AND status = \'finished\') BEGIN SELECT RAISE (ABORT, \'completed schedule must reference its finished session\');END',
    'schedule_entry_completed_session_on_insert',
  );
  final i1.Trigger scheduleEntryCompletedSessionOnUpdate = i1.Trigger(
    'CREATE TRIGGER schedule_entry_completed_session_on_update BEFORE UPDATE OF status, session_id, workout_id ON schedule_entry WHEN NEW.status = \'completed_by_session\' AND NOT EXISTS (SELECT 1 FROM session WHERE id = NEW.session_id AND schedule_entry_id = NEW.id AND workout_id = NEW.workout_id AND status = \'finished\') BEGIN SELECT RAISE (ABORT, \'completed schedule must reference its finished session\');END',
    'schedule_entry_completed_session_on_update',
  );
  final i1.Trigger sessionCompletedScheduleStatusOnUpdate = i1.Trigger(
    'CREATE TRIGGER session_completed_schedule_status_on_update BEFORE UPDATE OF status, workout_id ON session WHEN EXISTS (SELECT 1 FROM schedule_entry WHERE session_id = OLD.id AND status = \'completed_by_session\') AND(NEW.status <> \'finished\' OR NEW.workout_id IS NOT OLD.workout_id)BEGIN SELECT RAISE (ABORT, \'cannot invalidate completed schedule session link\');END',
    'session_completed_schedule_status_on_update',
  );
  late final Shape6 sessionExercise = Shape6(
    source: i0.VersionedTable(
      entityName: 'session_exercise',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CONSTRAINT session_exercise_order CHECK(order_index >= 0)',
        'CONSTRAINT session_exercise_planned_sets CHECK(planned_sets >= 1)',
        'CONSTRAINT session_exercise_rest CHECK(planned_rest_seconds >= 0)',
        'CONSTRAINT session_exercise_superset CHECK(superset_group IS NULL OR superset_group >= 0)',
        'CONSTRAINT session_exercise_rep_fields CHECK((planned_rep_type = \'fixed\' AND planned_target_reps IS NOT NULL AND planned_target_reps >= 1 AND planned_min_reps IS NULL AND planned_max_reps IS NULL)OR(planned_rep_type = \'range\' AND planned_target_reps IS NULL AND planned_min_reps IS NOT NULL AND planned_max_reps IS NOT NULL AND planned_min_reps >= 1 AND planned_max_reps >= planned_min_reps)OR(planned_rep_type = \'amrap\' AND planned_target_reps IS NULL AND planned_min_reps IS NULL AND planned_max_reps IS NULL))',
        'CONSTRAINT session_exercise_load_fields CHECK((planned_load_type = \'none\' AND planned_weight_canonical_mg IS NULL AND planned_percentage IS NULL AND planned_target_rpe IS NULL AND planned_freeform_text IS NULL)OR(planned_load_type = \'bodyweight\' AND planned_weight_canonical_mg IS NULL AND planned_percentage IS NULL AND planned_target_rpe IS NULL AND planned_freeform_text IS NULL)OR(planned_load_type = \'absolute\' AND planned_weight_canonical_mg IS NOT NULL AND planned_weight_canonical_mg >= 0 AND planned_percentage IS NULL AND planned_target_rpe IS NULL AND planned_freeform_text IS NULL)OR(planned_load_type = \'percentage\' AND planned_percentage IS NOT NULL AND planned_percentage >= 0 AND planned_percentage <= 100 AND planned_weight_canonical_mg IS NULL AND planned_target_rpe IS NULL AND planned_freeform_text IS NULL)OR(planned_load_type = \'target_rpe\' AND planned_target_rpe IS NOT NULL AND planned_target_rpe >= 0 AND planned_target_rpe <= 10 AND planned_weight_canonical_mg IS NULL AND planned_percentage IS NULL AND planned_freeform_text IS NULL)OR(planned_load_type = \'text\' AND planned_freeform_text IS NOT NULL AND length(planned_freeform_text) > 0 AND planned_weight_canonical_mg IS NULL AND planned_percentage IS NULL AND planned_target_rpe IS NULL))',
      ],
      columns: [
        _column_2,
        _column_39,
        _column_40,
        _column_8,
        _column_9,
        _column_10,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index sessionExerciseParentOrder = i1.Index(
    'session_exercise_parent_order',
    'CREATE UNIQUE INDEX session_exercise_parent_order ON session_exercise (session_id, order_index)',
  );
  final i1.Index sessionExerciseNormalizedName = i1.Index(
    'session_exercise_normalized_name',
    'CREATE INDEX session_exercise_normalized_name ON session_exercise (normalized_name)',
  );
  late final Shape7 sessionSet = Shape7(
    source: i0.VersionedTable(
      entityName: 'session_set',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CONSTRAINT session_set_index CHECK(set_index >= 0)',
        'CONSTRAINT session_set_rpe CHECK(rpe IS NULL OR(rpe >= 0 AND rpe <= 10))',
        'CONSTRAINT session_set_completion CHECK((completed = 0 AND completed_at IS NULL)OR(completed = 1 AND completed_at IS NOT NULL))',
        'CONSTRAINT session_set_planned_rep_fields CHECK((planned_rep_type = \'fixed\' AND planned_target_reps IS NOT NULL AND planned_target_reps >= 1 AND planned_min_reps IS NULL AND planned_max_reps IS NULL)OR(planned_rep_type = \'range\' AND planned_target_reps IS NULL AND planned_min_reps IS NOT NULL AND planned_max_reps IS NOT NULL AND planned_min_reps >= 1 AND planned_max_reps >= planned_min_reps)OR(planned_rep_type = \'amrap\' AND planned_target_reps IS NULL AND planned_min_reps IS NULL AND planned_max_reps IS NULL))',
        'CONSTRAINT session_set_planned_load_fields CHECK((planned_load_type = \'none\' AND planned_weight_canonical_mg IS NULL AND planned_percentage IS NULL AND planned_target_rpe IS NULL AND planned_freeform_text IS NULL)OR(planned_load_type = \'bodyweight\' AND planned_weight_canonical_mg IS NULL AND planned_percentage IS NULL AND planned_target_rpe IS NULL AND planned_freeform_text IS NULL)OR(planned_load_type = \'absolute\' AND planned_weight_canonical_mg IS NOT NULL AND planned_weight_canonical_mg >= 0 AND planned_percentage IS NULL AND planned_target_rpe IS NULL AND planned_freeform_text IS NULL)OR(planned_load_type = \'percentage\' AND planned_percentage IS NOT NULL AND planned_percentage >= 0 AND planned_percentage <= 100 AND planned_weight_canonical_mg IS NULL AND planned_target_rpe IS NULL AND planned_freeform_text IS NULL)OR(planned_load_type = \'target_rpe\' AND planned_target_rpe IS NOT NULL AND planned_target_rpe >= 0 AND planned_target_rpe <= 10 AND planned_weight_canonical_mg IS NULL AND planned_percentage IS NULL AND planned_freeform_text IS NULL)OR(planned_load_type = \'text\' AND planned_freeform_text IS NOT NULL AND length(planned_freeform_text) > 0 AND planned_weight_canonical_mg IS NULL AND planned_percentage IS NULL AND planned_target_rpe IS NULL))',
        'CONSTRAINT session_set_actual_rep_fields CHECK((actual_rep_type IS NULL AND actual_target_reps IS NULL AND actual_min_reps IS NULL AND actual_max_reps IS NULL)OR(actual_rep_type = \'fixed\' AND actual_target_reps IS NOT NULL AND actual_target_reps >= 1 AND actual_min_reps IS NULL AND actual_max_reps IS NULL)OR(actual_rep_type = \'range\' AND actual_target_reps IS NULL AND actual_min_reps IS NOT NULL AND actual_max_reps IS NOT NULL AND actual_min_reps >= 1 AND actual_max_reps >= actual_min_reps)OR(actual_rep_type = \'amrap\' AND actual_target_reps IS NULL AND actual_min_reps IS NULL AND actual_max_reps IS NULL))',
        'CONSTRAINT session_set_actual_load_fields CHECK((actual_load_type IS NULL AND actual_weight_canonical_mg IS NULL AND actual_percentage IS NULL AND actual_target_rpe IS NULL AND actual_freeform_text IS NULL)OR(actual_load_type = \'none\' AND actual_weight_canonical_mg IS NULL AND actual_percentage IS NULL AND actual_target_rpe IS NULL AND actual_freeform_text IS NULL)OR(actual_load_type = \'bodyweight\' AND actual_weight_canonical_mg IS NULL AND actual_percentage IS NULL AND actual_target_rpe IS NULL AND actual_freeform_text IS NULL)OR(actual_load_type = \'absolute\' AND actual_weight_canonical_mg IS NOT NULL AND actual_weight_canonical_mg >= 0 AND actual_percentage IS NULL AND actual_target_rpe IS NULL AND actual_freeform_text IS NULL)OR(actual_load_type = \'percentage\' AND actual_percentage IS NOT NULL AND actual_percentage >= 0 AND actual_percentage <= 100 AND actual_weight_canonical_mg IS NULL AND actual_target_rpe IS NULL AND actual_freeform_text IS NULL)OR(actual_load_type = \'target_rpe\' AND actual_target_rpe IS NOT NULL AND actual_target_rpe >= 0 AND actual_target_rpe <= 10 AND actual_weight_canonical_mg IS NULL AND actual_percentage IS NULL AND actual_freeform_text IS NULL)OR(actual_load_type = \'text\' AND actual_freeform_text IS NOT NULL AND length(actual_freeform_text) > 0 AND actual_weight_canonical_mg IS NULL AND actual_percentage IS NULL AND actual_target_rpe IS NULL))',
      ],
      columns: [
        _column_2,
        _column_51,
        _column_23,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index sessionSetParentOrder = i1.Index(
    'session_set_parent_order',
    'CREATE UNIQUE INDEX session_set_parent_order ON session_set (session_exercise_id, set_index)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get archivedAt =>
      columnsByName['archived_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'notes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'archived_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get workoutId =>
      columnsByName['workout_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get normalizedName =>
      columnsByName['normalized_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get orderIndex =>
      columnsByName['order_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plannedSets =>
      columnsByName['planned_sets']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get repType =>
      columnsByName['rep_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get targetReps =>
      columnsByName['target_reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get minReps =>
      columnsByName['min_reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get maxReps =>
      columnsByName['max_reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get loadType =>
      columnsByName['load_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get weightCanonicalMg =>
      columnsByName['weight_canonical_mg']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get percentage =>
      columnsByName['percentage']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get targetRpe =>
      columnsByName['target_rpe']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get freeformText =>
      columnsByName['freeform_text']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get restSeconds =>
      columnsByName['rest_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get supersetGroup =>
      columnsByName['superset_group']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'workout_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES workout(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'normalized_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'order_index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'planned_sets',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'rep_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'target_reps',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'min_reps',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'max_reps',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'load_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'weight_canonical_mg',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'percentage',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<double> _column_18(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'target_rpe',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'freeform_text',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rest_seconds',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'superset_group',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get workoutExerciseId =>
      columnsByName['workout_exercise_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get setIndex =>
      columnsByName['set_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get repType =>
      columnsByName['rep_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get targetReps =>
      columnsByName['target_reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get minReps =>
      columnsByName['min_reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get maxReps =>
      columnsByName['max_reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get loadType =>
      columnsByName['load_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get weightCanonicalMg =>
      columnsByName['weight_canonical_mg']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get percentage =>
      columnsByName['percentage']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get targetRpe =>
      columnsByName['target_rpe']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get freeformText =>
      columnsByName['freeform_text']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get restSeconds =>
      columnsByName['rest_seconds']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'workout_exercise_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES workout_exercise(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'set_index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get workoutId =>
      columnsByName['workout_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get scheduleEntryId =>
      columnsByName['schedule_entry_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get workoutNameSnapshot =>
      columnsByName['workout_name_snapshot']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endedAt =>
      columnsByName['ended_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get timezone =>
      columnsByName['timezone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get restStartedAt =>
      columnsByName['rest_started_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get restDurationSeconds =>
      columnsByName['rest_duration_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get restTargetAt =>
      columnsByName['rest_target_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'workout_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'REFERENCES workout(id)ON DELETE SET NULL',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'schedule_entry_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'REFERENCES schedule_entry(id)ON DELETE SET NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'workout_name_snapshot',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'started_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ended_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'timezone',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rest_started_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rest_duration_seconds',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rest_target_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get workoutId =>
      columnsByName['workout_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startTime =>
      columnsByName['start_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get label =>
      columnsByName['label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'workout_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES workout(id)ON DELETE RESTRICT',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'start_time',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'label',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'session_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'REFERENCES session(id)ON DELETE RESTRICT',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get nameSnapshot =>
      columnsByName['name_snapshot']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get normalizedName =>
      columnsByName['normalized_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get orderIndex =>
      columnsByName['order_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plannedSets =>
      columnsByName['planned_sets']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get plannedRepType =>
      columnsByName['planned_rep_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get plannedTargetReps =>
      columnsByName['planned_target_reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plannedMinReps =>
      columnsByName['planned_min_reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plannedMaxReps =>
      columnsByName['planned_max_reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get plannedLoadType =>
      columnsByName['planned_load_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get plannedWeightCanonicalMg =>
      columnsByName['planned_weight_canonical_mg']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plannedPercentage =>
      columnsByName['planned_percentage']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get plannedTargetRpe =>
      columnsByName['planned_target_rpe']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get plannedFreeformText =>
      columnsByName['planned_freeform_text']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get plannedRestSeconds =>
      columnsByName['planned_rest_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get supersetGroup =>
      columnsByName['superset_group']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'session_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES session(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name_snapshot',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'planned_rep_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'planned_target_reps',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'planned_min_reps',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'planned_max_reps',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'planned_load_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'planned_weight_canonical_mg',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_47(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'planned_percentage',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<double> _column_48(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'planned_target_rpe',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'planned_freeform_text',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'planned_rest_seconds',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sessionExerciseId =>
      columnsByName['session_exercise_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get setIndex =>
      columnsByName['set_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get plannedRepType =>
      columnsByName['planned_rep_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get plannedTargetReps =>
      columnsByName['planned_target_reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plannedMinReps =>
      columnsByName['planned_min_reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plannedMaxReps =>
      columnsByName['planned_max_reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get plannedLoadType =>
      columnsByName['planned_load_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get plannedWeightCanonicalMg =>
      columnsByName['planned_weight_canonical_mg']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plannedPercentage =>
      columnsByName['planned_percentage']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get plannedTargetRpe =>
      columnsByName['planned_target_rpe']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get plannedFreeformText =>
      columnsByName['planned_freeform_text']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get actualRepType =>
      columnsByName['actual_rep_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get actualTargetReps =>
      columnsByName['actual_target_reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get actualMinReps =>
      columnsByName['actual_min_reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get actualMaxReps =>
      columnsByName['actual_max_reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get actualLoadType =>
      columnsByName['actual_load_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get actualWeightCanonicalMg =>
      columnsByName['actual_weight_canonical_mg']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get actualPercentage =>
      columnsByName['actual_percentage']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get actualTargetRpe =>
      columnsByName['actual_target_rpe']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get actualFreeformText =>
      columnsByName['actual_freeform_text']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rpe =>
      columnsByName['rpe']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get completed =>
      columnsByName['completed']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plannedRestSeconds =>
      columnsByName['planned_rest_seconds']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_51(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'session_exercise_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES session_exercise(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'actual_rep_type',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'actual_target_reps',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_54(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'actual_min_reps',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_55(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'actual_max_reps',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'actual_load_type',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'actual_weight_canonical_mg',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'actual_percentage',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<double> _column_59(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'actual_target_rpe',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'actual_freeform_text',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<double> _column_61(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'rpe',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_62(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'completed',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_63(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'completed_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_64(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'planned_rest_seconds',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'CHECK (planned_rest_seconds IS NULL OR planned_rest_seconds >= 0)',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
